# Based on this: https://stackoverflow.com/a/52414495/5013410

matrix:
  include:
    - language: node_js
      node_js:
        - 10.16
        - 12.13
      install:
        - git submodule init
        - git submodule update
        - yarn install --offline
      script:
        - yarn build
        - yarn test

    - language: go
      go:
        - 1.12
        - 1.13
      script:
        - go build
        - go test ./...
