// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'layout': string;
  'menu': string;
  'menuBack': string;
  'menuLink': string;
  'menuList': string;
}
declare var cssExports: CssExports;
export = cssExports;
