name: Build App Client and Server

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        go: ['1.12', '1.13']

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - run: |
        git submodule init
        git submodule update

    - run: |
        yarn install --offline
        yarn build
        yarn test

    - run: |
        go build
        go test ./...
